### PR TITLE
Allow to add titles to feeds

### PR DESCRIPTION
**Pull request by nylnook**
A better tentative ?
Successfully tested.

As you have understood, I'm a drawer, not a coder... so your guidance is really welcome !

Cheers !

### CODE REVIEW

**Comment by hurrymaplelad** [comment]
Awesome!  You're a drawer *and* a coder!

**Comment by hurrymaplelad** [comment]
Published as `v2.3.0`

**Comment by nylnook** [comment]
;)

**Comment by nylnook** [comment]
Hmm...
after updating my install, with docpad-plugin-rss v2.3.0...
if I check my node_modules/docpad-plugin-rss/out directory, the rss.plugin.js file does not contain any change with the "title: site.title"...
So titles aren't modified...
I'm sorry I may have done something wrong, but the feature isn't really added...

maybe an issue with coffescript to javascript generation ?
No idea how to fix this...

**Comment by hurrymaplelad** [comment]
Whoops, right you are!  Forgot to run `cake compile`.  Republished as `v2.3.1`, that should do it.

**Comment by nylnook** [comment]
Great you spotted the bug so quick !
Thanks a lot for your work, it's now fixed, and I have my titles ;) 
nylnook/nylnook-webite@a6fda7018acb8156dbdec042f9c424a2de82d17f

**Pull request merged**
